export const CANVAS = { width: 1280, height: 720 };

export const COLORS = {
  tileLight: "#e2eaf1",
  tileDark: "#cdd9e6",
  grout: "#9aa9bd",
  pipeOuter: "#3a4255",
  pipeInner: "#161a26",
  pipeShine: "#5a6378",
  pathFlow: "#5a4b30",
  exitGlow: "#ff6b3d",
  toiletPorcelain: "#f3f6fa",
  sinkPorcelain: "#e8edf3",
  warningYellow: "#f6d96a",
  warningRed: "#e9534b",
  invoiceCream: "#fbf6e7",
  invoiceInk: "#1a1814",
  money: "#f6d96a",
  pipeMeterGood: "#5acf80",
  pipeMeterMid: "#f6d96a",
  pipeMeterBad: "#e9534b",
  hpBack: "#3a1418",
  hpFront: "#e9534b",
  hpArmored: "#a4b0c2",
  textPrimary: "#f3f5ff",
  textSecondary: "#a9b3c7",
  textMuted: "#6c7691",
  panelBg: "rgba(14, 18, 30, 0.92)",
  panelEdge: "#2a3148",
  panelHighlight: "#4ea1ff",
  buttonBg: "#1f2638",
  buttonHover: "#2c3650",
  buttonActive: "#3a4670",
  okGreen: "#5acf80",
  acidGreen: "#a8e07d",
  vacuumBlue: "#6fb8ff",
  stunBlue: "#d6ecff",
  poisonGreen: "#7be58c",
  brown: "#6b4a2b",
};

export const ECONOMY = {
  startingMoney: 200000,
  startingLives: 3,
  sellRefundRate: 0.7,
  killBaseMoney: 80,
  waveBonusBase: 3000,
  waveBonusGrowth: 450,
};

export const DIFFICULTY = {
  easy: {
    id: "easy",
    name: "출장",
    nameEn: "Easy",
    hpMul: 0.7,
    speedMul: 0.9,
    moneyMul: 1.4,
    livesBonus: 2,
    description: "출장비만 받고 가는 코스. 5층 평화로움.",
  },
  normal: {
    id: "normal",
    name: "관통기",
    nameEn: "Normal",
    hpMul: 1.0,
    speedMul: 1.0,
    moneyMul: 1.0,
    livesBonus: 0,
    description: "표준 관통 작업. 진짜 변기 막힘 수준.",
  },
  hard: {
    id: "hard",
    name: "고압세척",
    nameEn: "Hard",
    hpMul: 1.4,
    speedMul: 1.08,
    moneyMul: 0.85,
    livesBonus: -1,
    description: "고압 세척 출동. 김반장 직접 출동.",
  },
};

export const ENEMIES = {
  wetwipe: {
    id: "wetwipe",
    name: "물티슈",
    nameEn: "Wet Wipe",
    hp: 95,
    speed: 32,
    money: 175,
    radius: 12,
    color: "#7eb8ff",
    accent: "#a9d2ff",
    armor: 1,
    flags: { chemicalResist: 0.4 },
    icon: "🧻",
    threat: 4,
    weakness: "뚫어뻥 / 석션 / 산성 웅덩이",
  },
  paper: {
    id: "paper",
    name: "휴지",
    nameEn: "Toilet Paper",
    hp: 30,
    speed: 60,
    money: 75,
    radius: 10,
    color: "#f7e8c8",
    accent: "#fff7e3",
    armor: 0,
    flags: { cluster: true },
    icon: "🧻",
    threat: 1,
    weakness: "화학 (광역)",
  },
  lens: {
    id: "lens",
    name: "콘택트렌즈",
    nameEn: "Contact Lens",
    hp: 28,
    speed: 78,
    money: 100,
    radius: 7,
    color: "#a9efe5",
    accent: "#e2fbf7",
    armor: 0,
    flags: { evasive: 0.35 },
    icon: "👁",
    threat: 2,
    weakness: "렌즈 용해제 (화학 B)",
  },
  cap: {
    id: "cap",
    name: "인공눈물 껍데기",
    nameEn: "Eye-Drop Cap",
    hp: 70,
    speed: 44,
    money: 125,
    radius: 11,
    color: "#dfe7f3",
    accent: "#ffffff",
    armor: 1,
    flags: { split: { childType: "micro", count: 2 } },
    icon: "💊",
    threat: 3,
    weakness: "마스터 배관공 (분열 X)",
  },
  micro: {
    id: "micro",
    name: "미세 잔해",
    nameEn: "Micro Debris",
    hp: 22,
    speed: 72,
    money: 45,
    radius: 6,
    color: "#cfd6e3",
    accent: "#eef2fa",
    armor: 0,
    flags: { spawned: true },
    icon: "·",
    threat: 1,
  },
  kitchen: {
    id: "kitchen",
    name: "키친타월",
    nameEn: "Kitchen Towel",
    hp: 260,
    speed: 26,
    money: 600,
    radius: 14,
    color: "#f2bf5d",
    accent: "#ffd887",
    armor: 4,
    flags: { elite: true, forbidden: true },
    icon: "🟨",
    threat: 8,
    weakness: "공업용 석션 (보너스 ×2.4)",
  },
  boss: {
    id: "boss",
    name: "정체불명의 물질",
    nameEn: "Unidentifiable Matter",
    hp: 6000,
    speed: 14,
    money: 12000,
    radius: 30,
    color: "#5e3b1f",
    accent: "#8b5a2b",
    armor: 5,
    flags: {
      boss: true,
      adaptiveImmunity: true,
      knockbackResist: 0.92,
      slowResist: 0.7,
      stunResist: 0.85,
    },
    icon: "👹",
    threat: 80,
    weakness: "다양화 + 타이밍 능동 도구 (E·R·F)",
  },
};

export const TOWERS = {
  plunger: {
    id: "plunger",
    name: "뚫어뻥",
    nameEn: "Plunger Tower",
    color: "#d44a4a",
    accent: "#7a2c2c",
    desc: "할머니 시대부터 검증된 그것. 물리적으로 밀어냅니다.",
    base: {
      cost: 12000,
      range: 110,
      damage: 28,
      fireRate: 0.75,
      projectileSpeed: 580,
      projectileType: "plunger",
      pushback: 32,
    },
    branches: {
      A: {
        id: "double",
        name: "더블 액션",
        nameEn: "Double-Action",
        desc: "한 손으로 두 번 두드린다. 기사 팔 아파짐.",
        tier1: {
          cost: 17000,
          range: 125,
          damage: 26,
          fireRate: 0.36,
          pushback: 20,
        },
        tier2: {
          cost: 34000,
          range: 135,
          damage: 38,
          fireRate: 0.2,
          pushback: 26,
          passive: {
            id: "kineticShock",
            label: "운동 충격",
            desc: "푸시 시 잡몹(휴지·렌즈·미세잔해) 8% 즉사",
            instakillChance: 0.08,
            instakillTypes: ["paper", "lens", "micro"],
          },
        },
      },
      B: {
        id: "vacuum",
        name: "진공 뚫어뻥",
        nameEn: "Vacuum Plunger",
        desc: "진공 흡입. 적을 경로 뒤로 끌어당김. 귀마개 필수.",
        tier1: {
          cost: 19000,
          range: 140,
          damage: 22,
          fireRate: 0.9,
          pushback: 85,
          aoeRadius: 55,
        },
        tier2: {
          cost: 36000,
          range: 160,
          damage: 32,
          fireRate: 0.8,
          pushback: 145,
          aoeRadius: 75,
          passive: {
            id: "blackHole",
            label: "블랙홀 흡입",
            desc: "AOE 내 모든 적을 함께 끌어당김 (현재 구현됨)",
          },
        },
      },
    },
  },
  suction: {
    id: "suction",
    name: "석션",
    nameEn: "Suction Pump",
    color: "#4d8c66",
    accent: "#27553d",
    desc: "김반장 애용. 가벼운 잔해는 한 방. 키친타월은 공업용으로.",
    base: {
      cost: 20000,
      range: 145,
      damage: 26,
      fireRate: 0.9,
      projectileSpeed: 740,
      projectileType: "suction",
      critChance: 0.3,
      critMul: 6,
      armorPierce: 3,
    },
    branches: {
      A: {
        id: "industrial",
        name: "공업용 석션",
        nameEn: "Industrial Suction",
        desc: "산업현장 등급. 키친타월에게 ×2.4 보너스. 김반장 추천.",
        tier1: {
          cost: 28000,
          range: 145,
          damage: 32,
          fireRate: 1.0,
          critChance: 0.28,
          critMul: 6,
          armorPierce: 3,
          bonusVs: ["kitchen"],
          bonusMul: 2.4,
        },
        tier2: {
          cost: 45000,
          range: 165,
          damage: 52,
          fireRate: 0.95,
          critChance: 0.32,
          critMul: 7,
          armorPierce: 6,
          bonusVs: ["kitchen", "boss"],
          bonusMul: 2.8,
          passive: {
            id: "obliterator",
            label: "공업 분쇄기",
            desc: "키친타월 크리트 시 100% 즉사",
            critInstakillTypes: ["kitchen"],
          },
        },
      },
      B: {
        id: "reverse",
        name: "역류",
        nameEn: "Reverse Flow",
        desc: "역류 펄스. 4층에 흘러갈 뻔한 거 다시 5층으로.",
        tier1: {
          cost: 26000,
          range: 140,
          damage: 16,
          fireRate: 1.4,
          critChance: 0.2,
          critMul: 4,
          armorPierce: 1,
          stun: { radius: 80, duration: 1.4 },
        },
        tier2: {
          cost: 43000,
          range: 160,
          damage: 24,
          fireRate: 1.3,
          critChance: 0.25,
          critMul: 4,
          armorPierce: 2,
          stun: { radius: 110, duration: 2.2 },
          passive: {
            id: "cascadeStun",
            label: "연쇄 마비",
            desc: "스턴된 적 주변 인접 적 모두 0.8초 스턴",
            cascadeRadius: 60,
            cascadeStunDuration: 0.8,
          },
        },
      },
    },
  },
  chemical: {
    id: "chemical",
    name: "배수구 세정제",
    nameEn: "Chemical Tower",
    color: "#7e63d1",
    accent: "#3e2f72",
    desc: "락스 + 빙초산. 환기 안 시키면 5층이 잠깁니다.",
    base: {
      cost: 20000,
      range: 180,
      damage: 24,
      fireRate: 1.05,
      projectileSpeed: 460,
      projectileType: "chemical",
      aoeRadius: 78,
    },
    branches: {
      A: {
        id: "acidic",
        name: "강산성",
        nameEn: "Acidic Brew",
        desc: "강산성 웅덩이. 5분 후 4층 천장 누수 가능성.",
        tier1: {
          cost: 30000,
          range: 145,
          damage: 18,
          fireRate: 1.5,
          aoeRadius: 65,
          acidPool: { dps: 34, duration: 7, radius: 58 },
        },
        tier2: {
          cost: 47000,
          range: 200,
          damage: 26,
          fireRate: 1.4,
          aoeRadius: 80,
          acidPool: { dps: 58, duration: 9, radius: 75 },
          passive: {
            id: "bossEroder",
            label: "보스 부식",
            desc: "산성 웅덩이가 보스에게 +60% 데미지",
            bossBonusMul: 1.6,
          },
        },
      },
      B: {
        id: "lens",
        name: "렌즈 용해제",
        nameEn: "Lens Solvent",
        desc: "콘택트렌즈 즉사 + 시력 -0.5 회복불가. ₩5만 추가.",
        tier1: {
          cost: 28000,
          range: 145,
          damage: 16,
          fireRate: 1.2,
          aoeRadius: 60,
          bonusVs: ["lens"],
          bonusMul: 5,
        },
        tier2: {
          cost: 43000,
          range: 175,
          damage: 24,
          fireRate: 1.1,
          aoeRadius: 75,
          bonusVs: ["lens", "cap", "micro"],
          bonusMul: 4,
          passive: {
            id: "solventSupreme",
            label: "용해 절대권",
            desc: "렌즈/캡/마이크로는 단발 즉사",
            instakillTypes: ["lens", "cap", "micro"],
          },
        },
      },
    },
  },
  barracks: {
    id: "barracks",
    name: "배관공 양성소",
    nameEn: "Plumber Barracks",
    color: "#c79b56",
    accent: "#7a5828",
    desc: "기사 직접 출동. 호스 5층까지 끌고 오는 중. ₩2만/명.",
    base: {
      cost: 18000,
      range: 90,
      fireRate: 0,
      projectileType: "barracks",
      unitCount: 2,
      unitHp: 120,
      unitDamage: 26,
      unitAttackRate: 0.65,
      unitRespawn: 8,
    },
    branches: {
      A: {
        id: "master",
        name: "마스터 배관공",
        nameEn: "Master Plumber",
        desc: "30년 경력. 인공눈물 분열 없이 처리. 시급 ₩4.6만.",
        tier1: {
          cost: 28000,
          range: 125,
          unitCount: 1,
          unitHp: 260,
          unitDamage: 34,
          unitAttackRate: 0.75,
          unitRespawn: 10,
          cleanKill: ["cap"],
        },
        tier2: {
          cost: 46000,
          range: 135,
          unitCount: 1,
          unitHp: 440,
          unitDamage: 56,
          unitAttackRate: 0.65,
          unitRespawn: 8,
          cleanKill: ["cap"],
          passive: {
            id: "regenAura",
            label: "재생 오라",
            desc: "마스터 배관공이 매초 12HP 자가 회복",
            regenPerSec: 12,
          },
        },
      },
      B: {
        id: "apprentice",
        name: "견습 분대",
        nameEn: "Apprentice Squad",
        desc: "견습 4명. 호스 4개. 동시에 4개 막힘 처리. 단가 인하.",
        tier1: {
          cost: 24000,
          range: 115,
          unitCount: 4,
          unitHp: 62,
          unitDamage: 13,
          unitAttackRate: 0.6,
          unitRespawn: 8,
        },
        tier2: {
          cost: 42000,
          range: 125,
          unitCount: 4,
          unitHp: 105,
          unitDamage: 22,
          unitAttackRate: 0.5,
          unitRespawn: 7,
          passive: {
            id: "swarmFury",
            label: "분대 격분",
            desc: "유닛 1명 사망 시 남은 유닛 +35% 데미지 (8초)",
            comradeFurySec: 8,
            comradeFuryMul: 1.35,
          },
        },
      },
    },
  },
};

export const HEROES = {
  cheolsable: {
    id: "cheolsable",
    name: "철사블",
    nameEn: "Cheolsable",
    role: "The Funder · 후원자",
    icon: "💰",
    color: "#f6d96a",
    passive: "시작 ₩ +30% · 처치 보상 +5% (현금왕)",
    active: '"Pay the Invoice" — 화면 잔해 일소 + 보스 30% 피해',
    abilityName: "Pay the Invoice",
    abilityCost: 80000,
    abilityCooldown: 40,
    quote: "결제하면 다 해결돼.",
  },
  jeffrey: {
    id: "jeffrey",
    name: "제프리",
    nameEn: "Jeffrey",
    role: "The Organizer · 운영진",
    icon: "📋",
    color: "#6fb8ff",
    passive: "타워 건설/업그레이드 비용 -5%",
    active: "Rules Poster — 4초 혼란 (무료, 쿨다운 50s)",
    abilityName: "Rules Poster",
    abilityCost: 0,
    abilityCooldown: 50,
    quote: "여기 규칙 똑똑히 봐주세요.",
  },
  seongjin: {
    id: "seongjin",
    name: "민성진",
    nameEn: "Min Seongjin",
    role: "The Diagnostician · 진단가",
    icon: "🩺",
    color: "#a8e07d",
    passive: "모든 적 약점·HP 상시 표시 · 모든 타워 DMG +10%",
    active: "Diagnostic Scan — 6초 모든 타워 +50% DMG · 보스 면역 무효",
    abilityName: "Diagnostic Scan",
    abilityCost: 40000,
    abilityCooldown: 35,
    quote: "이건 그냥… 안 내려가는 거잖아요.",
  },
};

export const TIPS = [
  "키친타월 절대 금물. — 노마다마스 5F 벽 글귀.",
  "물티슈 화학저항 40%. 산성 웅덩이로 천천히 녹입니다.",
  "콘택트렌즈는 회피율 35%. 렌즈 용해제로 즉사.",
  "보스(정체불명의 물질)는 매번 다른 타워에 면역. 4종 다양화.",
  "출장비 ₩3만 별도. 부가세 포함. 야간 +₩8만.",
  "막힘 한 번 = ₩1,500,000. 김반장 출동.",
  "배관공 양성소: 기사 직접 출동. 호스 5층까지.",
  '치트: "150"을 타이핑하면 ₩1,500,000 + 보스 즉시 등장.',
  "고압세척 난이도는 진짜로 어렵습니다. 정신 차리세요.",
  "변기톤 — 화요일 데모데이까지 출시!",
  "Sisyphus Labs 토큰 후원: 연규 Kim.",
  "역류 석션은 경로 일부를 마비시킵니다.",
  "Tip: 콤보 8+ 보너스 +50%. 콜드 페이즈 가즈아.",
  "Tip: Vacuum Plunger II는 AOE 흡입.",
  "노마다마스 5F WiFi: tuesday2024_demoday.",
];

export const INVOICE = {
  company: "노마다마스 배관 출장 (5F 전담)",
  phone: "02-1577-키친타월금물",
  address: "서울특별시 어딘가 5층 (엘리베이터 없음)",
  items: [
    { label: "고압 세척 (5층 호스 추가)", price: 750000 },
    { label: "키친타월 제거 (3개소)", price: 380000 },
    { label: "물티슈 분해 시도 실패", price: 90000 },
    { label: "야간 출장 + 데모데이 직전", price: 110000 },
    { label: "콘택트렌즈 수거 (1짝)", price: 50000 },
    { label: "장비 손모 + 김반장 정신적 피해", price: 90000 },
    { label: "재방문 진단 (3개월 보증 X)", price: 30000 },
  ],
  vat: "부가세 포함 (현금시 ₩50,000 할인)",
  dispatch: "출장비 별도 ₩30,000 · 야간 +₩8만",
  warranty: "A/S 불가 · 키친타월 검출 시 즉시 무효",
  total: 1500000,
  smallPrint: "Sisyphus Labs · NomaDamas 5F · Toilet-thon 협찬",
};

export const BOSS_ABILITIES = {
  immunityRotationSec: 5.5,
  acidBurstCooldownSec: 10,
  acidBurstTowerDisableSec: 3,
  acidBurstRange: 180,
  sludgeSpawnHpThreshold: 0.5,
  sludgeSpawnCooldownSec: 5,
  deathThroesHpThreshold: 0.15,
  deathThroesSpeedMul: 2.2,
  enragedHpThreshold: 0.5,
  enragedSpeedMul: 1.35,
};

export const TOOLS = {
  rapidFlush: {
    id: "rapidFlush",
    name: "응급 분사",
    nameEn: "Rapid Flush",
    icon: "🚿",
    key: "E",
    cost: 0,
    cooldownSec: 18,
    radius: 90,
    pushback: 70,
    damage: 24,
    desc: "경로 클릭 → 80px 반경 적 밀어내기 + 24 dmg",
    color: "#6fb8ff",
  },
  barricade: {
    id: "barricade",
    name: "임시 차단막",
    nameEn: "Emergency Barricade",
    icon: "🛑",
    key: "R",
    cost: 30000,
    cooldownSec: 28,
    durationSec: 5,
    radius: 38,
    desc: "경로 클릭 → 5초간 그 지점 모든 적 차단",
    color: "#f6d96a",
  },
  kimDispatch: {
    id: "kimDispatch",
    name: "김반장 출장",
    nameEn: "Kim Dispatch",
    icon: "📞",
    key: "F",
    cost: 150000,
    cooldownSec: 75,
    damage: 320,
    stunSec: 3,
    desc: "보스/최강 적에게 320 dmg + 화면 모든 적 3초 스턴",
    color: "#e9534b",
  },
};

export const CREDITS = {
  studio: "Sisyphus Labs",
  team: "NomaDamas",
  event: "변기톤 (Toilet-thon)",
  sponsor: "토큰 스폰서: 연규 Kim",
  thanks: [
    "철사블 — for paying the invoice",
    "제프리 — for organizing the chaos",
    "민성진 — for the diagnosis",
    "5층 변기 — for the inspiration",
    "고압세척 트럭 — for the relief",
    "김반장 — 단가는 매분기 인상되지만 실력은 진짜",
    "키친타월 — 절대 금물 (학습용 빌런)",
    "노마다마스 5F WiFi — tuesday2024_demoday",
    "치트 힌트 — '150' 외에도 숨겨진 4개 있음",
  ],
};
