export const LEVELS = [
  {
    id: "sink",
    name: "세면대",
    nameEn: "The Sink",
    subtitle: "5F 세면대 → P트랩 → 2채널 분기 → 재합류 → 본관",
    paths: [
      [
        { x: 70, y: 60 },
        { x: 70, y: 200 },
        { x: 220, y: 200 },
        { x: 220, y: 260 },
        { x: 320, y: 260 },
        { x: 320, y: 160 },
        { x: 690, y: 160 },
        { x: 690, y: 400 },
        { x: 880, y: 400 },
        { x: 880, y: 600 },
        { x: 1010, y: 600 },
      ],
      [
        { x: 70, y: 60 },
        { x: 70, y: 200 },
        { x: 220, y: 200 },
        { x: 220, y: 260 },
        { x: 320, y: 260 },
        { x: 320, y: 380 },
        { x: 690, y: 380 },
        { x: 690, y: 400 },
        { x: 880, y: 400 },
        { x: 880, y: 600 },
        { x: 1010, y: 600 },
      ],
    ],
    entries: [{ x: 70, y: 60, kind: "sink", label: "세면대 (5F)" }],
    exits: [{ x: 1010, y: 600, kind: "sewer", label: "→ 4F 합류부" }],
    slots: [
      { x: 140, y: 135, zone: "ENTRY" },
      { x: 140, y: 200, zone: "ENTRY" },
      { x: 140, y: 270, zone: "ENTRY" },
      { x: 270, y: 135, zone: "FORK" },
      { x: 270, y: 215, zone: "FORK" },
      { x: 270, y: 330, zone: "FORK" },
      { x: 380, y: 110, zone: "TOP" },
      { x: 380, y: 210, zone: "TOP" },
      { x: 470, y: 110, zone: "TOP" },
      { x: 470, y: 210, zone: "TOP" },
      { x: 560, y: 110, zone: "TOP" },
      { x: 560, y: 210, zone: "TOP" },
      { x: 640, y: 110, zone: "TOP" },
      { x: 640, y: 210, zone: "TOP" },
      { x: 380, y: 330, zone: "BOT" },
      { x: 380, y: 430, zone: "BOT" },
      { x: 470, y: 330, zone: "BOT" },
      { x: 470, y: 430, zone: "BOT" },
      { x: 560, y: 330, zone: "BOT" },
      { x: 560, y: 430, zone: "BOT" },
      { x: 640, y: 330, zone: "BOT" },
      { x: 640, y: 430, zone: "BOT" },
      { x: 750, y: 280, zone: "REJOIN" },
      { x: 750, y: 400, zone: "REJOIN" },
      { x: 820, y: 280, zone: "REJOIN" },
      { x: 820, y: 480, zone: "EXIT" },
      { x: 820, y: 560, zone: "EXIT" },
      { x: 940, y: 440, zone: "EXIT" },
      { x: 940, y: 540, zone: "EXIT" },
      { x: 940, y: 640, zone: "EXIT" },
    ],
    startingMoney: 160000,
    waves: [
      {
        delay: 10,
        bonus: 2400,
        groups: [
          { type: "paper", count: 3, spacing: 1.0, path: 0 },
          { type: "paper", count: 3, spacing: 1.0, path: 1, delay: 2 },
        ],
      },
      {
        delay: 12,
        bonus: 2800,
        groups: [
          { type: "paper", count: 4, spacing: 0.85, path: 0 },
          { type: "paper", count: 4, spacing: 0.85, path: 1, delay: 3 },
          { type: "lens", count: 2, spacing: 1.6, path: 0, delay: 6 },
        ],
      },
      {
        delay: 12,
        bonus: 3200,
        groups: [
          { type: "lens", count: 3, spacing: 1.0, path: 0 },
          { type: "lens", count: 3, spacing: 1.0, path: 1, delay: 4 },
          { type: "paper", count: 5, spacing: 0.7, path: 0, delay: 7 },
        ],
      },
      {
        delay: 14,
        bonus: 3800,
        groups: [
          { type: "paper", count: 6, spacing: 0.55, path: 0 },
          { type: "paper", count: 6, spacing: 0.55, path: 1, delay: 2 },
          { type: "cap", count: 2, spacing: 1.6, path: 0, delay: 7 },
          { type: "wetwipe", count: 1, spacing: 0, path: 1, delay: 10 },
        ],
      },
      {
        delay: 14,
        bonus: 4400,
        groups: [
          { type: "lens", count: 4, spacing: 0.85, path: 0 },
          { type: "lens", count: 4, spacing: 0.85, path: 1, delay: 3 },
          { type: "cap", count: 3, spacing: 1.4, path: 0, delay: 7 },
          { type: "wetwipe", count: 2, spacing: 1.6, path: 0, delay: 11 },
        ],
      },
      {
        delay: 16,
        bonus: 5200,
        groups: [
          { type: "paper", count: 8, spacing: 0.5, path: 0 },
          { type: "paper", count: 8, spacing: 0.5, path: 1, delay: 1 },
          { type: "wetwipe", count: 3, spacing: 1.4, path: 0, delay: 6 },
          { type: "lens", count: 4, spacing: 0.9, path: 1, delay: 8 },
          { type: "cap", count: 2, spacing: 1.6, path: 1, delay: 12 },
        ],
      },
      {
        delay: 18,
        bonus: 6400,
        groups: [
          { type: "wetwipe", count: 4, spacing: 1.3, path: 0 },
          { type: "wetwipe", count: 4, spacing: 1.3, path: 1, delay: 2 },
          { type: "paper", count: 8, spacing: 0.5, path: 0, delay: 6 },
        ],
      },
      {
        delay: 16,
        bonus: 7400,
        groups: [
          { type: "wetwipe", count: 4, spacing: 1.3, path: 0 },
          { type: "wetwipe", count: 4, spacing: 1.3, path: 1, delay: 4 },
          { type: "paper", count: 8, spacing: 0.5, path: 0, delay: 8 },
        ],
      },
      {
        delay: 18,
        bonus: 9000,
        groups: [
          { type: "cap", count: 5, spacing: 1.0, path: 0 },
          { type: "cap", count: 5, spacing: 1.0, path: 1, delay: 3 },
          { type: "wetwipe", count: 6, spacing: 1.2, path: 0, delay: 8 },
          { type: "lens", count: 6, spacing: 0.7, path: 1, delay: 10 },
        ],
      },
      {
        delay: 20,
        bonus: 14000,
        boss: true,
        groups: [
          { type: "kitchen", count: 1, spacing: 0, path: 0 },
          { type: "kitchen", count: 1, spacing: 0, path: 1, delay: 1 },
          { type: "wetwipe", count: 5, spacing: 1.0, path: 0, delay: 5 },
          { type: "wetwipe", count: 5, spacing: 1.0, path: 1, delay: 6 },
          { type: "paper", count: 12, spacing: 0.4, path: 0, delay: 12 },
        ],
      },
    ],
    decor: {
      bathroom: "sink",
      floorLabel: "5F · 화장실 · 세면대 구역",
      signs: [
        { x: 460, y: 350, text: "키친타월 금물", color: "warning" },
        { x: 150, y: 460, text: "출장비 3만원", color: "sticker" },
        { x: 935, y: 360, text: "↓ 4F", color: "muted" },
        { x: 80, y: 420, text: "5F · 슬라브", color: "muted" },
        { x: 1080, y: 80, text: "DEMODAY D-2", color: "sticker" },
        { x: 80, y: 540, text: "₩150만 ABS", color: "sticker" },
        { x: 1100, y: 480, text: "tuesday2024_demoday", color: "muted" },
        { x: 410, y: 60, text: "Q4 OKR · 막힘 0건", color: "sticker" },
        { x: 1085, y: 220, text: "김반장 단가표", color: "muted" },
      ],
    },
  },

  {
    id: "toilet",
    name: "변기",
    nameEn: "The Toilet",
    subtitle: "5층 화장실 · 변기 + 세면대 → T자 합류 → 본관 진입",
    paths: [
      [
        { x: 160, y: 30 },
        { x: 160, y: 230 },
        { x: 540, y: 230 },
        { x: 540, y: 500 },
        { x: 540, y: 700 },
      ],
      [
        { x: 920, y: 30 },
        { x: 920, y: 230 },
        { x: 540, y: 230 },
        { x: 540, y: 500 },
        { x: 540, y: 700 },
      ],
    ],
    entries: [
      { x: 160, y: 30, kind: "toilet", label: "변기 (5F)" },
      { x: 920, y: 30, kind: "sink", label: "세면대 (5F)" },
    ],
    exits: [{ x: 540, y: 700, kind: "sewer", label: "→ 메인 오수관" }],
    slots: [
      { x: 95, y: 140, zone: "TA" },
      { x: 95, y: 200, zone: "TA" },
      { x: 240, y: 140, zone: "TA" },
      { x: 240, y: 200, zone: "TA" },
      { x: 850, y: 140, zone: "SA" },
      { x: 850, y: 200, zone: "SA" },
      { x: 990, y: 140, zone: "SA" },
      { x: 990, y: 200, zone: "SA" },
      { x: 280, y: 165, zone: "TH" },
      { x: 280, y: 295, zone: "TH" },
      { x: 350, y: 165, zone: "TH" },
      { x: 350, y: 295, zone: "TH" },
      { x: 415, y: 165, zone: "MERGE" },
      { x: 415, y: 295, zone: "MERGE" },
      { x: 460, y: 165, zone: "MERGE" },
      { x: 460, y: 295, zone: "MERGE" },
      { x: 540, y: 165, zone: "MERGE" },
      { x: 540, y: 295, zone: "MERGE" },
      { x: 620, y: 165, zone: "MERGE" },
      { x: 620, y: 295, zone: "MERGE" },
      { x: 665, y: 165, zone: "SH" },
      { x: 665, y: 295, zone: "SH" },
      { x: 730, y: 165, zone: "SH" },
      { x: 730, y: 295, zone: "SH" },
      { x: 800, y: 165, zone: "SH" },
      { x: 800, y: 295, zone: "SH" },
      { x: 430, y: 380, zone: "DROP" },
      { x: 650, y: 380, zone: "DROP" },
      { x: 430, y: 470, zone: "DROP" },
      { x: 650, y: 470, zone: "DROP" },
      { x: 430, y: 570, zone: "EXIT" },
      { x: 540, y: 540, zone: "EXIT" },
      { x: 650, y: 570, zone: "EXIT" },
      { x: 430, y: 660, zone: "EXIT" },
      { x: 540, y: 640, zone: "EXIT" },
      { x: 650, y: 660, zone: "EXIT" },
    ],
    startingMoney: 180000,
    waves: [
      {
        delay: 8,
        bonus: 2200,
        groups: [
          { type: "paper", count: 6, spacing: 0.7, path: 0 },
          { type: "lens", count: 2, spacing: 1.2, path: 1, delay: 4 },
        ],
      },
      {
        delay: 10,
        bonus: 2600,
        groups: [
          { type: "paper", count: 4, spacing: 0.6, path: 0 },
          { type: "paper", count: 4, spacing: 0.6, path: 1, delay: 3 },
        ],
      },
      {
        delay: 12,
        bonus: 3000,
        groups: [
          { type: "wetwipe", count: 4, spacing: 1.4, path: 0 },
          { type: "lens", count: 4, spacing: 0.9, path: 1, delay: 4 },
        ],
      },
      {
        delay: 12,
        bonus: 3600,
        groups: [
          { type: "paper", count: 8, spacing: 0.45, path: 0 },
          { type: "cap", count: 3, spacing: 1.2, path: 1, delay: 5 },
        ],
      },
      {
        delay: 14,
        bonus: 4200,
        groups: [
          { type: "wetwipe", count: 4, spacing: 1.4, path: 0 },
          { type: "wetwipe", count: 4, spacing: 1.4, path: 1, delay: 3 },
        ],
      },
      {
        delay: 14,
        bonus: 4800,
        groups: [
          { type: "wetwipe", count: 3, spacing: 1.2, path: 0 },
          { type: "paper", count: 10, spacing: 0.4, path: 0, delay: 4 },
          { type: "lens", count: 6, spacing: 0.7, path: 1, delay: 2 },
        ],
      },
      {
        delay: 14,
        bonus: 5400,
        groups: [
          { type: "cap", count: 6, spacing: 1.1, path: 0 },
          { type: "wetwipe", count: 4, spacing: 1.3, path: 0, delay: 6 },
          { type: "paper", count: 8, spacing: 0.5, path: 1, delay: 2 },
        ],
      },
      {
        delay: 16,
        bonus: 6800,
        groups: [
          { type: "kitchen", count: 1, spacing: 0, path: 0 },
          { type: "wetwipe", count: 6, spacing: 1.0, path: 0, delay: 4 },
          { type: "kitchen", count: 1, spacing: 0, path: 1, delay: 8 },
        ],
      },
      {
        delay: 18,
        bonus: 8000,
        groups: [
          { type: "wetwipe", count: 8, spacing: 0.9, path: 0 },
          { type: "cap", count: 4, spacing: 1.0, path: 0, delay: 6 },
          { type: "wetwipe", count: 6, spacing: 1.0, path: 1, delay: 2 },
        ],
      },
      {
        delay: 20,
        bonus: 12000,
        groups: [
          { type: "paper", count: 14, spacing: 0.35, path: 0 },
          { type: "wetwipe", count: 8, spacing: 0.8, path: 1, delay: 1 },
          { type: "kitchen", count: 2, spacing: 4, path: 0, delay: 10 },
        ],
      },
      {
        delay: 18,
        bonus: 13500,
        groups: [
          { type: "kitchen", count: 3, spacing: 2.2, path: 0 },
          { type: "wetwipe", count: 8, spacing: 0.9, path: 1, delay: 4 },
        ],
      },
      {
        delay: 18,
        bonus: 15000,
        groups: [
          { type: "cap", count: 10, spacing: 0.8, path: 0 },
          { type: "wetwipe", count: 8, spacing: 1.0, path: 1, delay: 5 },
          { type: "lens", count: 8, spacing: 0.6, path: 0, delay: 10 },
        ],
      },
      {
        delay: 20,
        bonus: 17000,
        groups: [
          { type: "wetwipe", count: 12, spacing: 0.8, path: 0 },
          { type: "wetwipe", count: 12, spacing: 0.8, path: 1, delay: 2 },
          { type: "kitchen", count: 3, spacing: 2.5, path: 0, delay: 8 },
        ],
      },
      {
        delay: 22,
        bonus: 22000,
        boss: true,
        groups: [
          { type: "kitchen", count: 5, spacing: 1.8, path: 0 },
          { type: "wetwipe", count: 10, spacing: 0.8, path: 1, delay: 4 },
          { type: "paper", count: 18, spacing: 0.35, path: 0, delay: 10 },
          { type: "cap", count: 6, spacing: 0.9, path: 1, delay: 16 },
        ],
      },
    ],
    decor: {
      bathroom: "toilet",
      floorLabel: "5F · 화장실 풀뷰 · T자 합류부",
      signs: [
        { x: 110, y: 380, text: "키친타월 금물", color: "warning" },
        { x: 990, y: 400, text: "출장비 3만원", color: "sticker" },
        { x: 540, y: 660, text: "↓ 본관 직결", color: "muted" },
        { x: 90, y: 600, text: "5F · 슬라브", color: "muted" },
        { x: 1000, y: 600, text: "5F · 슬라브", color: "muted" },
        { x: 90, y: 80, text: "Sisyphus Labs", color: "sticker" },
        { x: 1000, y: 80, text: "변기톤 · D-2", color: "sticker" },
        { x: 360, y: 535, text: "₩150만 ABSOLUTE", color: "sticker" },
        { x: 110, y: 685, text: "TOSS: pay.me/kim", color: "muted" },
        { x: 990, y: 685, text: "Q4 단가 인상", color: "muted" },
        { x: 760, y: 540, text: "물티슈 ≠ 변기", color: "warning" },
      ],
    },
  },

  {
    id: "mainpipe",
    name: "메인 오수관",
    nameEn: "Main Pipe",
    subtitle: "최종 결전 · 5F·4F·3F 동시 진입 → 수직 본관 → 보스",
    paths: [
      [
        { x: 60, y: 60 },
        { x: 60, y: 140 },
        { x: 820, y: 140 },
        { x: 820, y: 660 },
      ],
      [
        { x: 60, y: 240 },
        { x: 60, y: 320 },
        { x: 820, y: 320 },
        { x: 820, y: 660 },
      ],
      [
        { x: 60, y: 420 },
        { x: 60, y: 500 },
        { x: 820, y: 500 },
        { x: 820, y: 660 },
      ],
    ],
    entries: [
      { x: 60, y: 60, kind: "junction", label: "5F 진입" },
      { x: 60, y: 240, kind: "junction", label: "4F 진입" },
      { x: 60, y: 420, kind: "junction", label: "3F 진입" },
    ],
    exits: [{ x: 820, y: 660, kind: "sewer", label: "→ 본 하수관" }],
    slots: [
      { x: 140, y: 90, zone: "5F" },
      { x: 140, y: 200, zone: "5F" },
      { x: 240, y: 90, zone: "5F" },
      { x: 240, y: 200, zone: "5F" },
      { x: 380, y: 90, zone: "5F" },
      { x: 380, y: 200, zone: "5F" },
      { x: 520, y: 90, zone: "5F" },
      { x: 520, y: 200, zone: "5F" },
      { x: 660, y: 90, zone: "5F" },
      { x: 660, y: 200, zone: "5F" },
      { x: 140, y: 270, zone: "4F" },
      { x: 140, y: 380, zone: "4F" },
      { x: 240, y: 270, zone: "4F" },
      { x: 240, y: 380, zone: "4F" },
      { x: 380, y: 270, zone: "4F" },
      { x: 380, y: 380, zone: "4F" },
      { x: 520, y: 270, zone: "4F" },
      { x: 520, y: 380, zone: "4F" },
      { x: 660, y: 270, zone: "4F" },
      { x: 660, y: 380, zone: "4F" },
      { x: 140, y: 450, zone: "3F" },
      { x: 140, y: 560, zone: "3F" },
      { x: 240, y: 450, zone: "3F" },
      { x: 240, y: 560, zone: "3F" },
      { x: 380, y: 450, zone: "3F" },
      { x: 380, y: 560, zone: "3F" },
      { x: 520, y: 450, zone: "3F" },
      { x: 520, y: 560, zone: "3F" },
      { x: 660, y: 450, zone: "3F" },
      { x: 660, y: 560, zone: "3F" },
      { x: 880, y: 220, zone: "MAIN" },
      { x: 880, y: 400, zone: "MAIN" },
      { x: 880, y: 580, zone: "MAIN" },
      { x: 940, y: 220, zone: "MAIN" },
      { x: 940, y: 400, zone: "MAIN" },
      { x: 940, y: 580, zone: "MAIN" },
      { x: 750, y: 220, zone: "MAIN" },
      { x: 750, y: 400, zone: "MAIN" },
      { x: 750, y: 580, zone: "MAIN" },
    ],
    startingMoney: 220000,
    waves: [
      {
        delay: 10,
        bonus: 2600,
        groups: [
          { type: "paper", count: 8, spacing: 0.55, path: 0 },
          { type: "lens", count: 3, spacing: 1.0, path: 0, delay: 5 },
        ],
      },
      {
        delay: 12,
        bonus: 3000,
        groups: [
          { type: "wetwipe", count: 3, spacing: 1.1, path: 0 },
          { type: "paper", count: 6, spacing: 0.5, path: 1, delay: 3 },
        ],
      },
      {
        delay: 14,
        bonus: 3400,
        groups: [
          { type: "cap", count: 5, spacing: 1.0, path: 0 },
          { type: "wetwipe", count: 3, spacing: 1.1, path: 1, delay: 4 },
          { type: "paper", count: 6, spacing: 0.5, path: 0, delay: 6 },
        ],
      },
      {
        delay: 14,
        bonus: 4400,
        groups: [
          { type: "wetwipe", count: 5, spacing: 0.9, path: 0 },
          { type: "lens", count: 5, spacing: 0.7, path: 1, delay: 3 },
          { type: "cap", count: 3, spacing: 1.0, path: 2, delay: 6 },
        ],
      },
      {
        delay: 16,
        bonus: 5200,
        groups: [
          { type: "paper", count: 10, spacing: 0.35, path: 0 },
          { type: "paper", count: 8, spacing: 0.4, path: 1, delay: 3 },
          { type: "wetwipe", count: 4, spacing: 0.9, path: 2, delay: 6 },
        ],
      },
      {
        delay: 16,
        bonus: 5800,
        groups: [
          { type: "cap", count: 5, spacing: 0.9, path: 0 },
          { type: "lens", count: 6, spacing: 0.7, path: 1, delay: 5 },
          { type: "cap", count: 3, spacing: 1.0, path: 2, delay: 8 },
          { type: "kitchen", count: 1, spacing: 0, path: 0, delay: 12 },
        ],
      },
      {
        delay: 18,
        bonus: 7200,
        groups: [
          { type: "kitchen", count: 3, spacing: 2.0, path: 0 },
          { type: "wetwipe", count: 6, spacing: 0.8, path: 1, delay: 4 },
          { type: "wetwipe", count: 4, spacing: 1.0, path: 2, delay: 8 },
        ],
      },
      {
        delay: 18,
        bonus: 8800,
        groups: [
          { type: "wetwipe", count: 8, spacing: 0.7, path: 0 },
          { type: "wetwipe", count: 6, spacing: 0.8, path: 1, delay: 3 },
          { type: "cap", count: 6, spacing: 0.9, path: 2, delay: 8 },
        ],
      },
      {
        delay: 20,
        bonus: 11000,
        groups: [
          { type: "kitchen", count: 4, spacing: 1.5, path: 0 },
          { type: "kitchen", count: 2, spacing: 2.0, path: 1, delay: 4 },
          { type: "paper", count: 10, spacing: 0.4, path: 2, delay: 6 },
        ],
      },
      {
        delay: 20,
        bonus: 14000,
        groups: [
          { type: "kitchen", count: 3, spacing: 1.8, path: 0 },
          { type: "wetwipe", count: 10, spacing: 0.7, path: 1, delay: 4 },
          { type: "wetwipe", count: 8, spacing: 0.7, path: 2, delay: 8 },
        ],
      },
      {
        delay: 22,
        bonus: 18000,
        groups: [
          { type: "paper", count: 14, spacing: 0.3, path: 0 },
          { type: "lens", count: 8, spacing: 0.6, path: 1, delay: 3 },
          { type: "wetwipe", count: 8, spacing: 0.7, path: 2, delay: 6 },
          { type: "cap", count: 6, spacing: 0.9, path: 0, delay: 12 },
          { type: "kitchen", count: 2, spacing: 2.0, path: 1, delay: 16 },
        ],
      },
      {
        delay: 18,
        bonus: 20000,
        groups: [
          { type: "kitchen", count: 4, spacing: 1.6, path: 0 },
          { type: "kitchen", count: 3, spacing: 1.6, path: 1, delay: 3 },
          { type: "wetwipe", count: 8, spacing: 0.7, path: 2, delay: 6 },
        ],
      },
      {
        delay: 18,
        bonus: 22000,
        groups: [
          { type: "wetwipe", count: 14, spacing: 0.55, path: 0 },
          { type: "wetwipe", count: 10, spacing: 0.65, path: 1, delay: 3 },
          { type: "cap", count: 8, spacing: 0.8, path: 2, delay: 6 },
        ],
      },
      {
        delay: 20,
        bonus: 25000,
        groups: [
          { type: "kitchen", count: 4, spacing: 1.4, path: 0 },
          { type: "kitchen", count: 3, spacing: 1.5, path: 1, delay: 3 },
          { type: "wetwipe", count: 12, spacing: 0.6, path: 2, delay: 5 },
          { type: "lens", count: 10, spacing: 0.5, path: 0, delay: 11 },
        ],
      },
      {
        delay: 20,
        bonus: 28000,
        boss: true,
        groups: [
          { type: "kitchen", count: 5, spacing: 1.2, path: 0 },
          { type: "kitchen", count: 3, spacing: 1.4, path: 1, delay: 3 },
          { type: "wetwipe", count: 10, spacing: 0.7, path: 2, delay: 5 },
          { type: "paper", count: 16, spacing: 0.3, path: 0, delay: 10 },
        ],
      },
      {
        delay: 22,
        bonus: 32000,
        groups: [
          { type: "wetwipe", count: 12, spacing: 0.5, path: 0 },
          { type: "wetwipe", count: 10, spacing: 0.55, path: 1, delay: 3 },
          { type: "cap", count: 10, spacing: 0.8, path: 2, delay: 5 },
          { type: "kitchen", count: 5, spacing: 1.3, path: 0, delay: 10 },
          { type: "lens", count: 10, spacing: 0.5, path: 1, delay: 14 },
        ],
      },
      {
        delay: 24,
        bonus: 40000,
        groups: [
          { type: "kitchen", count: 5, spacing: 1.0, path: 0 },
          { type: "kitchen", count: 4, spacing: 1.1, path: 1, delay: 3 },
          { type: "wetwipe", count: 12, spacing: 0.6, path: 2, delay: 5 },
          { type: "cap", count: 8, spacing: 0.7, path: 0, delay: 10 },
          { type: "paper", count: 18, spacing: 0.3, path: 1, delay: 15 },
        ],
      },
      {
        delay: 30,
        bonus: 80000,
        boss: true,
        groups: [
          { type: "wetwipe", count: 6, spacing: 0.9, path: 0 },
          { type: "wetwipe", count: 6, spacing: 0.9, path: 1, delay: 2 },
          { type: "kitchen", count: 3, spacing: 2.0, path: 2, delay: 6 },
          { type: "boss", count: 1, spacing: 0, path: 0, delay: 14 },
          { type: "wetwipe", count: 10, spacing: 0.5, path: 1, delay: 18 },
          { type: "wetwipe", count: 8, spacing: 0.55, path: 2, delay: 22 },
          { type: "kitchen", count: 4, spacing: 1.8, path: 0, delay: 28 },
          { type: "paper", count: 18, spacing: 0.3, path: 1, delay: 34 },
        ],
      },
    ],
    decor: {
      bathroom: "mainpipe",
      floorLabel: "본관 수직 단면 · 5F→4F→3F",
      signs: [
        { x: 410, y: 110, text: "고압세척 주의", color: "warning" },
        { x: 870, y: 580, text: "출장비 3만원", color: "sticker" },
        { x: 50, y: 380, text: "5F 슬라브", color: "muted" },
        { x: 360, y: 420, text: "4F 슬라브", color: "muted" },
        { x: 720, y: 660, text: "3F 슬라브", color: "muted" },
        { x: 250, y: 380, text: "키친타월 금물", color: "warning" },
        { x: 540, y: 420, text: "물티슈 금물", color: "warning" },
        { x: 50, y: 660, text: "노마다마스 본관 단면", color: "muted" },
        { x: 1050, y: 80, text: "BOSS LEVEL", color: "warning" },
        { x: 80, y: 100, text: "P0 INCIDENT", color: "sticker" },
        { x: 1080, y: 540, text: "₩150만 × 3 = ₩450만", color: "sticker" },
        { x: 540, y: 80, text: "데모데이 D-1 (긴급)", color: "warning" },
        { x: 1080, y: 380, text: "Sisyphus Labs", color: "sticker" },
        { x: 80, y: 580, text: "MTTR 30분 목표", color: "muted" },
        { x: 540, y: 600, text: "고압 호스 ₩200만", color: "sticker" },
      ],
    },
  },
];
